[tool.poetry]
name = "pythonproject9"
version = "0.1.0"
description = "\"\""
authors = ["Tarabukina Olga"]
license = "\"\""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
